
package lk.ijse.SPRDA.View;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.SPRDA.Controller.JobController;
import lk.ijse.SPRDA.Controller.TotalCurrentlyJob;
import lk.ijse.SPRDA.model.Job;


public class AddJob extends javax.swing.JFrame {

    
    public AddJob() {
        initComponents();
        loadAllCurrentlyJob();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtEmp_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbDesignation = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbDistrictOffice = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDivisionalOffice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAddJob = new javax.swing.JButton();
        btnUpdateJob = new javax.swing.JButton();
        btnDeleteJob = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(149, 165, 166));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(java.awt.Color.darkGray);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Job Details");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/road couple.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-970, -120, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/road couple.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1840, -80, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 500));

        txtEmp_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtEmp_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 320, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        cmbDesignation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbDesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Districk Engineer", "Divisional Engineer", "Technical officer", "Work superviser", "Office staff", "Clark", "Leybour", "Driver", "Watchman" }));
        cmbDesignation.setBorder(null);
        jPanel1.add(cmbDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 300, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Designation");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        cmbDistrictOffice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbDistrictOffice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Galle", "Mathara", "Hambanthota" }));
        cmbDistrictOffice.setBorder(null);
        jPanel1.add(cmbDistrictOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 320, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("District Office");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        txtDivisionalOffice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtDivisionalOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 300, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Divisional Office");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        btnAddJob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddJob.setText("Add");
        btnAddJob.setBorder(null);
        btnAddJob.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnAddJobAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                btnAddJobAncestorRemoved(evt);
            }
        });
        btnAddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJobActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 110, 30));

        btnUpdateJob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateJob.setText("Update ");
        btnUpdateJob.setBorder(null);
        btnUpdateJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateJobActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 110, 30));

        btnDeleteJob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteJob.setText("Delete");
        btnDeleteJob.setBorder(null);
        btnDeleteJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteJobActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Designation", "District Office", "Divisional Office"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 760, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         new DashBoardView().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnAddJobAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnAddJobAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddJobAncestorAdded

    private void btnAddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJobActionPerformed
        
        try {
            String Ep_id=txtEmp_ID.getText();
            String Designation=cmbDesignation.getSelectedItem().toString();
            String District_Office=cmbDistrictOffice.getSelectedItem().toString();
            String Divisional_Office=txtDivisionalOffice.getText();
            
            Job j1=new Job(
                    Ep_id,
                    Designation,
                    District_Office,
                    Divisional_Office
            );
            
            
            
            boolean isSaved=new JobController().saveJob(j1);
            
            if(isSaved){
                JOptionPane.showMessageDialog(null, "Saved");
            }else{
                JOptionPane.showMessageDialog(null, "Try again");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddJob.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAddJobActionPerformed

    private void btnAddJobAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnAddJobAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddJobAncestorRemoved

    private void btnDeleteJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteJobActionPerformed
        
        if(txtEmp_ID.getText().trim().length()>3){
            try {
                
                if(new JobController().dropJob(txtEmp_ID.getText().trim())){
                    JOptionPane.showMessageDialog(null, "DELETED");
                }else{
                    JOptionPane.showMessageDialog(null, "Something went Wrong!!!","WARNING",JOptionPane.WARNING_MESSAGE);
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddJob.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AddJob.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please Insert an ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDeleteJobActionPerformed

    private void btnUpdateJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateJobActionPerformed
        
        if(txtEmp_ID.getText().trim().length()>3){  
            
            try {
                String Ep_id=txtEmp_ID.getText();
                String Designation=cmbDesignation.getSelectedItem().toString();
                String District_Office=cmbDistrictOffice.getSelectedItem().toString();
                String Divisional_Office=txtDivisionalOffice.getText();
                
                Job j1=new Job(Ep_id,Designation,District_Office,Divisional_Office);
                
                if(new JobController().updateState(j1)){
                    JOptionPane.showMessageDialog(null, "Done... ");
                }else{
                    JOptionPane.showMessageDialog(null, "Please try again","WARNING",JOptionPane.WARNING_MESSAGE);
                }
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddJob.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AddJob.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please insert an ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnUpdateJobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJob;
    private javax.swing.JButton btnDeleteJob;
    private javax.swing.JButton btnUpdateJob;
    private javax.swing.JComboBox<String> cmbDesignation;
    private javax.swing.JComboBox<String> cmbDistrictOffice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDivisionalOffice;
    private javax.swing.JTextField txtEmp_ID;
    // End of variables declaration//GEN-END:variables

    private void loadAllCurrentlyJob() {
        
        try {
            
            List<Job> jobList= new TotalCurrentlyJob().getAllJobs();
            
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            
            for(Job tempJob:jobList){
                model.addRow(new Object[]{
                    tempJob.getEp_id(),
                    tempJob.getDesignation(),
                    tempJob.getDistrict_Office(),
                    tempJob.getDivisional_Office(),
              
               });
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TotalCurrentlyEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TotalCurrentlyEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
    }
}
