/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.SPRDA.View;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.SPRDA.Controller.LoansController;
import lk.ijse.SPRDA.Controller.TotalCurrentlyJob;
import lk.ijse.SPRDA.Controller.TotalCurrentlyLoans;
import lk.ijse.SPRDA.model.Job;
import lk.ijse.SPRDA.model.Loans;

/**
 *
 * @author HP
 */
public class AddLoans extends javax.swing.JFrame {

    /**
     * Creates new form AddLoans
     */
    public AddLoans() {
        initComponents();
        loadAllCurrentlyLoans();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLoanId = new javax.swing.JTextField();
        txtEP_ID = new javax.swing.JTextField();
        txtLoanAmount = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        jbtnAdd = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbLoanType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(189, 195, 199));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(149, 165, 166));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Loans");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/road couple.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1040, -130, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Loan Types");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 220, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assests/road couple.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1830, -120, 2100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 500));

        txtLoanId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLoanId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoanIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtLoanId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 310, 30));

        txtEP_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtEP_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 290, 30));

        txtLoanAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtLoanAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 310, 30));

        txtDuration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 290, 30));

        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 130, 30));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 130, 30));

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Employee ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Loan ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Loan Amount");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Duration");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Loan Type");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        cmbLoanType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "House Loans", "Vehical Loans", "Special Loans", "Disaster Loans", "Personal Loans" }));
        jPanel1.add(cmbLoanType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 310, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loan ID", "Employee ID", "Loan Amount", "Duration", "Loan Type"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 770, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new DashBoardView().setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void txtLoanIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoanIdActionPerformed
        
        if(txtLoanId.getText().trim().length()>0){
            try {
                
            
                Loans  obj=new LoansController().getLoans(txtLoanId.getText().trim());
            
                if(obj!=null){
                    txtEP_ID.setText(obj.getEp_id());
                    txtLoanAmount.setText(obj.getLoan_amount());
                    txtDuration.setText(obj.getDuration());
                    cmbLoanType.setSelectedItem(obj.getLoan_type());
                }else{
                    JOptionPane.showMessageDialog(this, "No Result Found","Warning",JOptionPane.WARNING_MESSAGE);
                }
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Please Insert an ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_txtLoanIdActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        
        try {
            String Loan_id=txtLoanId.getText();
            String Ep_id=txtEP_ID.getText();
            String Loan_amount=txtLoanAmount.getText();
            String Duration=txtDuration.getText();
            String Loan_type=cmbLoanType.getSelectedItem().toString();
            
            Loans l1=new Loans(
                    Loan_id,
                    Ep_id,
                    Loan_amount,
                    Duration,
                    Loan_type
            );
               
         boolean isSaved=new LoansController().saveLoans(l1);
         
         if(isSaved){
             JOptionPane.showMessageDialog(null, "Saved..");
         }else{
             JOptionPane.showMessageDialog(null, "Try Again..");
         }
         
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        
        if(txtLoanId.getText().trim().length()>0){
            try {
                
                
                if (new LoansController().dropLoans(txtLoanId.getText().trim())){
                    JOptionPane.showMessageDialog(null, "Deleted...");
                }else{
                    JOptionPane.showMessageDialog(null, "Someone went Wrong!!","WARNING",JOptionPane.WARNING_MESSAGE);
                }
            
            
            } catch (SQLException ex) {
                Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please Insert an ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
            String Loan_id=txtLoanId.getText();
            String Ep_id=txtEP_ID.getText();
            String Loan_amount=txtLoanAmount.getText();
            String Duration=txtDuration.getText();
            String Loan_type=cmbLoanType.getSelectedItem().toString();
            
            Loans l1=new Loans(
                    Loan_id,
                    Ep_id,
                    Loan_amount,
                    Duration,
                    Loan_type
            );
        
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        
        if(txtLoanId.getText().trim().length()>0){
         
            try {
                String Loan_id=txtLoanId.getText();
                String Ep_id=txtEP_ID.getText();
                String Loan_amount=txtLoanAmount.getText();
                String Duration=txtDuration.getText();
                String Loan_type=cmbLoanType.getSelectedItem().toString();
                
                Loans l1=new Loans(Loan_id,Ep_id,Loan_amount,Duration,Loan_type);
                
                if(new LoansController().updateState(l1)){
                    JOptionPane.showMessageDialog(null, "Done..");
                }else{
                    JOptionPane.showMessageDialog(null, "Please Try Again..","WARNING",JOptionPane.WARNING_MESSAGE);
                }
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        }else{
            JOptionPane.showMessageDialog(null, "Please Insert an ID","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLoans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLoans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbLoanType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtEP_ID;
    private javax.swing.JTextField txtLoanAmount;
    private javax.swing.JTextField txtLoanId;
    // End of variables declaration//GEN-END:variables

    private void loadAllCurrentlyLoans() {
        
        try {
            List<Loans> LoansList=new TotalCurrentlyLoans().getAllLoans();
            
            DefaultTableModel modal=(DefaultTableModel) jTable1.getModel();
            
            for(Loans tempLoans:LoansList){
                
                modal.addRow(new Object[]{
                    tempLoans.getLoan_id(),
                    tempLoans.getEp_id(),
                    tempLoans.getLoan_amount(),
                    tempLoans.getDuration(),
                    tempLoans.getLoan_type()
                        
                
                });
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddLoans.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}
